sprint3 done
monsterr00/metric-service pull request #4
Opened 2024-04-26 20:26 UTC by monsterr00

2024-04-29 12:08 UTC, arttet requested changes

2024-04-29 12:08 UTC, arttet commented on cmd/server/storelayer/store.go
> +	SELECT EXISTS (
CHANGE REQUEST: please use migrations

2024-05-13 14:28 UTC, monsterr00 commented on cmd/server/storelayer/store.go
> +	SELECT EXISTS (
done

2024-05-20 08:46 UTC, arttet approved these changes

2024-05-20 08:46 UTC, arttet commented on cmd/server/storelayer/store.go
> +	_ "github.com/golang-migrate/migrate/v4/source/file"
Please sort these imports

2024-05-20 08:46 UTC, arttet commented on db/migrations/000001_create_metrics_table.up.sql
> +CREATE TABLE IF NOT EXISTS metrics (
```suggestion
CREATE TABLE metrics (
```

2024-05-20 08:46 UTC, arttet commented on db/migrations/000001_create_metrics_table.up.sql
> +	MType varchar(255),
It should be `enum`

2024-05-20 08:46 UTC, arttet commented on internal/helpers/helpers.go
> +	if path.Base(cwd) == "metric-service" { //проверяем, запущено из корня бинарником тестов или нет
This is a strange function. Please remove it.

2024-06-10 14:31 UTC, merged