Iter14
monsterr00/metric-service pull request #5
Opened 2024-05-26 14:31 UTC by monsterr00

2024-05-31 08:15 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил пару комментов по улучшению кода

2024-05-31 08:15 UTC, gonozov0 commented on cmd/agent/httplayer/workersPool.go
> +		}
У тебя эта конструкция не будет работать как ты ожидаешь, т.к. p.wg.Wait() заблокирует весь поток и будет ждать пока не отработают все воркеры. А если в каком-то из воркеров возникнет ошибка, то у тебя навсегда все зависнет, т.к. он будет писать в небуферизированный канал ошибок, блокироваться, пока кто-то из него не прочитает, а никто из него прочитать больше не сможет)

2024-05-31 08:15 UTC, gonozov0 commented on cmd/agent/httplayer/workersPool.go
> +	p.wg.Done()
лучше через defer в начале функции

2024-05-31 08:15 UTC, gonozov0 commented on cmd/agent/httplayer/workersPool.go
> +		}
Для этих целей тебе нужно создать и смотреть в select на контекст

2024-05-31 08:15 UTC, gonozov0 commented on cmd/agent/httplayer/workersPool.go
> +	queue  chan *resty.Request
Не вижу чтобы где-то закрывались каналы, по хорошему должен быть метод Stop

2024-06-07 20:07 UTC, monsterr00 commented on cmd/agent/httplayer/workersPool.go
> +		}
done

2024-06-07 20:14 UTC, monsterr00 commented on cmd/agent/httplayer/workersPool.go
> +	p.wg.Done()
убрал совсем, насколько я понял, обработка ctx.Done() дает такой же эффект, как и sync.WaitGroup

2024-06-07 20:14 UTC, monsterr00 commented on cmd/agent/httplayer/workersPool.go
> +	queue  chan *resty.Request
done

2024-06-08 17:55 UTC, gonozov0 approved these changes
Все моменты поправлены 👍

2024-06-10 14:31 UTC, merged